### ISSUE TITLE
Configurable blockchains

### ISSUE THREAD

**Issue by jmsm412** [rairprotocol/rair-dapp#105]
Add, remove and update blockchain information through the server settings.

**Comment by rairprotocol** [comment]
Add hardhat deployment recipe to markdown. From there will convert to gitbook

**Comment by jayson687** [comment]
Believe my guys,  d a r k w e b p r o g r a m m e r @ g m a i l . c o m    are the best when comes to hacks transfer, they got me $15,000![image](https://github.com/user-attachments/assets/246fed18-e847-4eb1-a221-03031d48c97e)

**Comment by sarora180673** [comment]
Error while adding Blockchain from Settings
![Screenshot from 2024-07-29 13-03-18](https://github.com/user-attachments/assets/b9431cf1-26e8-4248-8ab9-6a3b35dfea61)

**Comment by sarora180673** [comment]
Getting error in rair-sync logs
RPC defined for Base is https://base.meowrpc.com   but error is coming for https://base-mainnet.g.alchemy.com/v2/demo
--
[utils/reusableTransactionHandler.js] timeout (requestBody="{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":42,\"jsonrpc\":\"2.0\"}", requestMethod="POST", timeout=120000, url="https://base-mainnet.g.alchemy.com/v2/demo", code=TIMEOUT, version=web/5.7.1)  - Error: timeout (requestBody="{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":42,\"jsonrpc\":\"2.0\"}", requestMethod="POST", timeout=120000, url="https://base-mainnet.g.alchemy.com/v2/demo", code=TIMEOUT, version=web/5.7.1)
    at Logger.makeError (/usr/src/event-listener/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Timeout._onTimeout (/usr/src/event-listener/node_modules/@ethersproject/web/lib/index.js:187:35)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7)
2024-07-29T07:57:48.129Z [error] : [tasks/index.js] Agenda > Fail: {"reason":"timeout","code":"TIMEOUT","requestBody":"{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":42,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","timeout":120000,"url":"https://base-mainnet.g.alchemy.com/v2/demo","level":"error"}

**Comment by sarora180673** [comment]
contract deployment having issues - not able to select blockchain from dropdown

![contractDeployment](https://github.com/user-attachments/assets/915668bf-ecdb-4b55-913a-78f0ade50c1d)

**Comment by sarora180673** [comment]
Switch Blockchain on clicking Easy Mint Button (Collection view) is not working
![Screenshot from 2024-07-29 19-58-42](https://github.com/user-attachments/assets/47fefa2b-fa39-485a-8f95-6145e5293833)

**Comment by RAIReth** [comment]
0x2b0fFbF00388f9078d5512256c43B983BB805eF8

**Comment by sarora180673** [comment]
> contract deployment having issues - not able to select blockchain from dropdown Also, Balance is shown as 0.0 Tokens
> 
> ![contractDeployment](https://private-user-images.githubusercontent.com/26207079/352965366-915668bf-ecdb-4b55-913a-78f0ade50c1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNjQyMDcsIm5iZiI6MTcyMjM2MzkwNywicGF0aCI6Ii8yNjIwNzA3OS8zNTI5NjUzNjYtOTE1NjY4YmYtZWNkYi00YjU1LTkxM2EtNzhmMGFkZTUwYzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE4MjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZTFkMWMxZDZiNmM2MmQ5ODYwYzY2ZDUzYmM0NzMyMWQ4YjcwNTEzYmYzNmZmYjdlMTJjMGY2MmRjYWM5NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B41YZAunfHx1N4tY6jBNY0aUaBZZ9d2TGbrNs6ARP0Y)

Issue was due to ERC20 address not configured from UI
