### ISSUE TITLE
Homepage class error issue in frontend preventing metadata image display

### ISSUE THREAD

**Issue by rairprotocol** [rairprotocol/rair-dapp#12]
Resolve class error

**Comment by sarora180673** [comment]
Collection Banners is also not loading

![Image](https://github.com/rairprotocol/rair-dapp/assets/26207079/0d563fdc-ea8f-4319-8840-1fb07626b89f)

**Comment by rairprotocol** [comment]
Arsenii to investigate - it worked then stopped working

**Comment by SeanM322** [comment]
@sarora180673 
branch - "add-hover-effect-for-admin-links"
