### ISSUE TITLE
Simple dApp (only login, profile page, single action)

### ISSUE THREAD

**Issue by rairadmin** [rairprotocol/rair-dapp#129]
Simplified sample version of rair-front that is only the user profile page as homepage. 

Add 1 new mechanic to do something fun. Collect NFT, or favorite something in the database to create the most simple single function dApp.

**Comment by rairadmin** [comment]
No rush on timing! Can get other tasks done as priority - just a fun side project to help out new devs

**Comment by rairadmin** [comment]
Something like this perhaps https://catattack.thirdweb.com/

**Comment by rairadmin** [comment]
Here is an example UI. Only functionality is to free mint our admin NFT for the hackathon. 
![simpledapp](https://github.com/user-attachments/assets/05ddd47a-7bb0-4d30-87e0-5502d9ec6fcb)

**Comment by gminx** [comment]
-Deployment: Checkin to rair-templates repo which have access to. Only checkin rair-front. Pull node, sync, media if needed from master repo

-Configuration of the mint button is handled in the environment variable.

-Button text. Contract, product,offer

-Simple dApp = true/false 1/0

-If set to true then it hides the entire marketplace and only displays the single mint button for the offer specified in the environment variable file.

**Comment by RAIReth** [comment]
get with Juan re random buy button logic for simple dapp

**Comment by RAIReth** [comment]
Simple dapp works!
