### ISSUE TITLE
Recipe for frontend adding new blockchains

### ISSUE THREAD

**Issue by rairadmin** [rairprotocol/rair-dapp#132]
How to add support for new blockchian to frontend. Ticker symbol, logo file, etc.

**Comment by RAIReth** [comment]
Link new blockchain to main file - then can use server settings.

**Comment by SeanM322** [comment]
PR - https://github.com/rairprotocol/rair-dapp/pull/157

I've added new blockchain in file `rair-front/src/utils/blockchainData.ts`
