### ISSUE TITLE
Investigate deploying dApp from multiple repos (rair-front + master repo)

### ISSUE THREAD

**Issue by RAIReth** [rairprotocol/rair-dapp#135]
See if we can build our dapp using different rair-fronts.

**Comment by sarora180673** [comment]
docker-compose can be created which pulls images from docker hub for all components except rair-front for achieving this task.

**Comment by gminx** [comment]
checkin just the rair-front folder into rair-templates. but let's call each one a unique name.

"rair-front-demo-button"
