### ISSUE TITLE
Investigate Hashicorp vault key system

### ISSUE THREAD

**Issue by rairprotocol** [rairprotocol/rair-dapp#15]
Ensure is still working properly on migrated open source system

**Comment by rairprotocol** [comment]
Hashicorp is working best not to touch it

**Comment by RAIReth** [comment]
1. demo account students can use and pre populate env. 2. how students can make their own vault credentials.

**Comment by RAIReth** [comment]
Will reopen as needed. Can work without vault but need specific env variables
