### ISSUE TITLE
Add documentation to each API param for further clarity

### ISSUE THREAD

**Issue by rairprotocol** [rairprotocol/rair-dapp#16]
Starting with Auth API calls

**Comment by rairprotocol** [comment]
start by just adding AUTH information to body params. Suresh/Juan to provide basic text - will add to existing gitbook as markdown

**Comment by rairprotocol** [comment]
Notate what each individual body param does.

**Comment by rairprotocol** [comment]
Investigate the flow from @zalcala transliterated master API yaml to keep our API up to date. How to update the yaml and keep all of the notes. 

How to slowly add individual body params.

**Comment by RAIReth** [comment]
Will document params for auth calls this sprint

**Comment by RAIReth** [comment]
Update this yaml file here so API is under version control. Then reference the version controlled yaml in the gitbook. 

https://github.com/rairprotocol/rair-dapp/blob/main/rair-node/readme/openapi/rairapi_current.yaml
