### ISSUE TITLE
Akash Network Docker Engine error. Not able to connect on Docker engine on up command

### ISSUE THREAD

**Issue by RAIReth** [rairprotocol/rair-dapp#170]
Tested on Akash plain linux. 

Ubuntu 24.04 with 4vcpu 16gb ram. 

SSH and all steps work.

Fails at the very last step of docker up. 

> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
> root@service-1-0:/mnt/data/RAIR/rair-dapp# sudo systemctl status docker
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down

--

For any community devs to try. Follow our command line guide here. (you just need to paste in all of the commands in order)

https://docs.rairprotocol.org/rairprotocol/installation-and-testing/getting-started

--

Akash config

![akash-config](https://github.com/user-attachments/assets/f0566398-6909-437e-bf62-51cafb95787a)

**Comment by sarora180673** [comment]
Error logs
---

root@service-1-0:/mnt/data/RAIR/rair-dapp# sudo /usr/local/bin/docker-compose -f docker-compose-web.yml up -d
WARN[0000] The "kohler_meeting_id" variable is not set. Defaulting to a blank string.
WARN[0000] The "yoti_client_id" variable is not set. Defaulting to a blank string.
WARN[0000] The "sentry_dsn" variable is not set. Defaulting to a blank string.
WARN[0000] The "sentry_dsn" variable is not set. Defaulting to a blank string.
WARN[0000] The "sentry_dsn" variable is not set. Defaulting to a blank string.
WARN[0000] /mnt/data/RAIR/rair-dapp/docker-compose-web.yml: `version` is obsolete
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
root@service-1-0:/mnt/data/RAIR/rair-dapp# sudo systemctl status docker
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
root@service-1-0:/mnt/data/RAIR/rair-dapp# sudo service docker restart
 * Stopping Docker: docker                                                                                                                    Program process in pidfile '/var/run/docker-ssd.pid', 1 process(es), refused to die.

**Comment by Zblocker64** [comment]
So your issue is that you’re trying to install docker and run docker inside a docker container. Let’s just run the docker container instead of installing Ubuntu and then installing docker

**Comment by RAIReth** [comment]
> Do you have a docker image that is available on docker hub?

That's an awesome insight @Zblocker64  - if we can run docker direct then we don't need to do this container inside a container thing.

Our docker hub is here. https://hub.docker.com/u/rairprotocol

each microservice node (backend) front sync and media can all be run from this preconfigured yaml file with an up -d compose command

https://github.com/rairprotocol/rair-dapp/blob/dev/docker-compose.local-new.yml

Will also try this on our end!

**Comment by Zblocker64** [comment]
There is no import, but it is relatively easy to transfer over the parameters. Also, I thought there was six? Including the mongo db and the redis. Or are those separate from this deployment?

**Comment by sarora180673** [comment]
Yes, mongodb, Redis and 4 other services (rair-front, rair-node, rair-stream, rair-sync)

**Comment by Zblocker64** [comment]
So this is the SDL I have built. You still need to add in all the environment variables, but once you do that I think it should work.

```---
version: "2.0"
services:
  mongo:
    image: mongo:latest
    expose:
      - port: 27017
        as: 27017
        proto: tcp
        to:
          - global: false
          - service: rair-front
          - service: rair-node
          - service: rair-stream
          - service: rair-sync
          - service: redis
  rair-front:
    image: rairprotocol/rair-front:fa6fef8daa324a35ac6d38f0f81c01a570d1bf06
    expose:
      - port: 8088
        as: 80
        to:
          - global: true
          - service: rair-node
          - service: rair-stream
          - service: rair-sync
          - service: redis
          - service: mongo
  rair-node:
    image: rairprotocol/rair-node:fa6fef8daa324a35ac6d38f0f81c01a570d1bf06
    expose:
      - port: 3000
        as: 3000
        proto: tcp
        to:
          - global: false
          - service: rair-front
          - service: rair-stream
          - service: rair-sync
          - service: redis
          - service: mongo
      - port: 5000
        as: 5000
        proto: tcp
        to:
          - global: false
          - service: rair-front
          - service: rair-stream
          - service: rair-sync
  rair-stream:
    image: rairprotocol/rair-stream:fa6fef8daa324a35ac6d38f0f81c01a570d1bf06
    expose:
      - port: 5002
        as: 5002
        proto: tcp
        to:
          - global: false
          - service: rair-front
          - service: rair-node
          - service: rair-sync
          - service: redis
          - service: mongo
  rair-sync:
    image: rairprotocol/rair-sync:fa6fef8daa324a35ac6d38f0f81c01a570d1bf06
    expose:
      - port: 5001
        as: 5001
        proto: tcp
        to:
          - global: false
          - service: rair-front
          - service: rair-node
          - service: rair-stream
          - service: redis
          - service: mongo
  redis:
    image: redis:6.2.3-alpine
    expose:
      - port: 6379
        as: 6379
        proto: tcp
        to:
          - global: false
          - service: rair-front
          - service: rair-node
          - service: rair-stream
          - service: rair-sync
          - service: mongo
    command:
      - "\"redis-server\""
    args:
      - "--protected-mode no"
profiles:
  compute:
    mongo:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          - size: 5Gi
    rair-front:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          - size: 5Gi
    rair-node:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          - size: 5Gi
    rair-stream:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          - size: 5Gi
    rair-sync:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          - size: 5Gi
    redis:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          - size: 5Gi
  placement:
    dcloud:
      pricing:
        mongo:
          denom: uakt
          amount: 1000
        rair-front:
          denom: uakt
          amount: 1000
        rair-node:
          denom: uakt
          amount: 1000
        rair-stream:
          denom: uakt
          amount: 1000
        rair-sync:
          denom: uakt
          amount: 1000
        redis:
          denom: uakt
          amount: 1000
deployment:
  mongo:
    dcloud:
      profile: mongo
      count: 1
  rair-front:
    dcloud:
      profile: rair-front
      count: 1
  rair-node:
    dcloud:
      profile: rair-node
      count: 1
  rair-stream:
    dcloud:
      profile: rair-stream
      count: 1
  rair-sync:
    dcloud:
      profile: rair-sync
      count: 1
  redis:
    dcloud:
      profile: redis
      count: 1
```

**Comment by Zblocker64** [comment]
If you want a provider to test it on let me know. I run a provider and can give you a steep discount for testing

**Comment by sarora180673** [comment]
Thanks,let me add environment variables and check if this SDL can be deployed on Plain Linux.

**Comment by RAIReth** [comment]
> If you want a provider to test it on let me know. I run a provider and can give you a steep discount for testing

We'd love that. Having a default in the vite.config.ts we can point to an Akash k8 instance would be epic. Then new devs can use the akash cloud version of our backend and just modify their rair-front microservice for their unique app logic

**Comment by Zblocker64** [comment]
Ok. Send me your wallet address so I can do some manual pricing for you for the next little bit. Once it’s up and running I’ll revert back to my normal pricing(it’s still cheep). If you have discord my username is Zblocker64

**Comment by RAIReth** [comment]
> Ok. Send me your wallet address so I can do some manual pricing for you for the next little bit. Once it’s up and running I’ll revert back to my normal pricing(it’s still cheep). If you have discord my username is Zblocker64

Awesome will ping you with the cosmos address on discord

**Comment by RAIReth** [comment]
Template SDL uploaded here https://console.akash.network/template/57e71df3-7342-41d9-8b9c-e2fb055e4ffb
