### ISSUE TITLE
Customization issue: Error encountered while uploading custom logo

### ISSUE THREAD

**Issue by niteenbalpande** [rairprotocol/rair-dapp#218]
### **I encountered an issue while trying to upload a custom logo. The following error pop-up appeared during the upload process:** 
_**Unable to upload image at the moment**_

**Steps to reproduce:**

- Navigate to the customization settings.
- Select the option to upload a custom logo.
- Attempt to upload a .png/.jpeg logo file.
- The error pop-up appears.

**Expected behavior:**

- The custom logo should be uploaded successfully without any errors.

**Actual behavior:**

- [ ] The logo upload fails, and an error pop-up is displayed.

**Browser log**
Request URL: http://localhost:8088/api/settings/appLogo
Request Method: POST
Status Code: 500 Internal Server Error
Referrer Policy: strict-origin-when-cross-origin 
![Screenshot 2024-09-16 131655](https://github.com/user-attachments/assets/daf649f3-ec29-441d-bc93-51c6c03f2471)

**Comment by jmsm412** [comment]
Hi, please check the IPFS_SERVICE value in your environment file, currently we support 'pinata' and 'filebase' for the ipfs services from https://pinata.cloud/ and https://filebase.com/ respectively.
If your service is pinata you'll need to set the PINATA_KEY, PINATA_SECRET, PINATA_GATEWAY values in your environment file.
If your service is filebase you'll only need to set the FILEBASE_BUCKET value in your environment file.

**Comment by niteenbalpande** [comment]
added pinata, web3auth, pinata gateway and admin contract address, shows error no user found pop up. is because of admin contract or is there any problem with web3auth.?
but there is another issue due to CSP which not allowing inline script injection in desktop mode " Content Security Policy of your site blocks the use of 'eval' in JavaScript" which not allowing js in desktop mode

**Comment by niteenbalpande** [comment]
tried with pinata, web3 auth, client id in frontend but landing page crashed in desktop view:" Cannot read properties of undefined (reading 'includes')". in mobile view working but error exist with no user address found, could be with gateway or web3 auth ?

env front
```
VITE_DEFAULT_BLOCKCHAIN=0x2105
VITE_WEB3AUTH_CLIENT_ID=08fe0b859c93e0b3693c34c499647bdff391a5ad6d9171969ca9937d1337ac6e
```

.env
```
#jwt_secret for decryption DEPRECATED
jwt_secret=
#pinata configuration
pinata_key=c6116fcec6fc***49815
pinata_secret=O1fxqK8ipe8*************qOWXRUVL-b29-CbdtwzSvOMLllp7Uk29TUTbd7aD
pinata_gateway=apricot-managing-kiwi****5.mypinata.cloud
```

https://github.com/user-attachments/assets/575550e9-2abc-41a0-bd9d-3be2aa8847c7

**Comment by sarora180673** [comment]
Please check if you have below variable in .env

ipfs_service=pinata

Also, you need to have Alchemy key defined in rair-front/.env  for social logins (otherwise you will get User Address issue). For example, if you have defined Base Blockchain (0x2105) as default then you should have below variable defined in rair-front/.env

VITE_BASE_MAINNET_ALCHEMY_KEY=xxxxxxxxxxxxxxxxxxxxxxx

**Comment by RAIReth** [comment]
Pinata cloud support currently depracted. Use filebase flow instead and logo uploads will work
