### ISSUE TITLE
Notifications not displayed on Mobile

### ISSUE THREAD

**Issue by sarora180673** [rairprotocol/rair-dapp#220]
Latest dev branch

Test scenario : Login with social and click on Bell icon (with notifications count displayed )

Observation : A new window is displayed but notifications are not shown. Only "Clear all"  button is shown
![notifications-mobile](https://github.com/user-attachments/assets/f0b5b624-1dbb-4bbf-b9ee-49f8e779b6c3)

**Comment by SeanM322** [comment]
@sarora180673 
PR - https://github.com/rairprotocol/rair-dapp/pull/229
