### ISSUE TITLE
Serial number picker - not showing all the ranges for selecting tokens

### ISSUE THREAD

**Issue by sarora180673** [rairprotocol/rair-dapp#236]
Latest dev  branch

Test environment :  Collection has 10000 tokens

Test case:  Try to select token number 9999 from Serial number picker

Observation :  Not all the ranges are shown in Serial number picker(it allows upto token 3000) , as a result token number e.g., 9999 can't be selected 

![Screenshot from 2024-10-03 13-15-25](https://github.com/user-attachments/assets/40e42105-8e42-4cb2-a4c7-1ef4bb199b82)

**Comment by SeanM322** [comment]
PR: https://github.com/rairprotocol/rair-dapp/pull/241
