### ISSUE TITLE
Sort functionality on Home Page is not working

### ISSUE THREAD

**Issue by sarora180673** [rairprotocol/rair-dapp#242]
Latest dev branch

Test case : 
Step -1 : Open Home page  e.g., https://rair.market/
Step -2 : Try "Sort by Name"  on MARKET Tab and also on Videos Tab

Observation :  Selecting Name: A-Z  or Name: Z-A is having no effect on the order in which Collections or Videos tiles are displayed

![Screenshot from 2024-10-07 21-59-36](https://github.com/user-attachments/assets/39b66c67-51f2-4054-ad1c-d63f549a9248)

**Comment by SeanM322** [comment]
PR - https://github.com/rairprotocol/rair-dapp/pull/251
Ready for testing
@sarora180673
