### ISSUE TITLE
"Clear all" Button should be disabled when no notifications exists

### ISSUE THREAD

**Issue by sarora180673** [rairprotocol/rair-dapp#243]
Latest dev branch

Test case :  Click on "Clear all" button when no notifications exists from Desktop / Mobile

Observation :  Clear all button is not disabled and user gets Success  message even though no notifications were deleted

Expected response :  "Clear all" Button should be disabled when no notifications exists

![Screenshot from 2024-10-08 12-56-26](https://github.com/user-attachments/assets/b425ff3f-9a18-4d70-8b54-955e07417f4e)

**Comment by SeanM322** [comment]
PR - https://github.com/rairprotocol/rair-dapp/pull/250
Ready for testing
@sarora180673
