### ISSUE TITLE
Metadata Filter with multiple Traits

### ISSUE THREAD

**Issue by sarora180673** [rairprotocol/rair-dapp#252]
Latest dev branch

Test case:  Select Multiple Traits in Metadata filter

Observation : Result contains NFTs which match ANY traits/attributes

Expected : Result set should contain NFTs which match ALL of the traits/attributes

Please also consider scenario where user select multiple attributes of a Trait - which I think should not be allowed based on new proposed logic

**Comment by RAIReth** [comment]
replace AND logic with OR for filtering attributes
