### ISSUE TITLE
Information related to Video Category is not provided on Video Management page

### ISSUE THREAD

**Issue by sarora180673** [rairprotocol/rair-dapp#253]
Latest dev branch

Test case :  SuperAdmin user navigates to Video management page  e.g., https://rair.market/user/videos

Observation : Information related to Category of Video is not provided on Video Management page.
![Screenshot from 2024-10-11 01-10-47](https://github.com/user-attachments/assets/163cf861-61c3-4ba7-afd8-47095173e89d)

If user modifies some property of video e.g., change Visible to Hidden etc, then Category is displayed on UI since API response in this case provides category info. But still it's not very clear on UI, what that text signifies.

![Screenshot from 2024-10-11 01-12-38](https://github.com/user-attachments/assets/6711bf3d-8864-45e6-ac43-6d21e6cccb25)

**Comment by RAIReth** [comment]
Update logic so super admins can control video category instead of just video uploader
