### ISSUE TITLE
Update docker compose with mongodb and download image from hub instead of repo - adjust github actions 

### ISSUE THREAD

**Issue by rairprotocol** [rairprotocol/rair-dapp#28]
-how can we create a new dockerhub image that will easily run remote

-remote is better - Arsenii to test drive 

-update github actions to understand which is latest images (added tags) - won't know what hash is

**Comment by sarora180673** [comment]
docker-compose-web.yml   can be used to start app using images available on docker hub.
Below command will start the app on local machine by downloading images from Docker hub

docker-compose -f docker-compose-web.yml up -d
