### ISSUE TITLE
Error message on clicking "Social Login" Button on Home Page

### ISSUE THREAD

**Issue by sarora180673** [rairprotocol/rair-dapp#35]
Error message on clicking "Social Login" Button on Home Page
![Screenshot from 2024-05-20 19-12-03](https://github.com/rairprotocol/rair-dapp/assets/26207079/7157a0e8-8b5b-40f2-aecf-fbd5f2886ca8)

**Comment by rairprotocol** [comment]
need to provide web3auth clientID - not a security issue as just the pub key

**Comment by rairprotocol** [comment]
initial flow works with new env update - need to get wallet to display in UI (check logs)
