### ISSUE TITLE
On Browser console showing error message "Failed to load resource: the server responded with a status of 403 ()"

### ISSUE THREAD

**Issue by sarora180673** [rairprotocol/rair-dapp#41]
On starting application with .env copied from .env.sample, Browser console is showing error messages 

"Failed to load resource: the server responded with a status of 403 ()" 

It's trying to fetch  https://rair.mypinata.cloud/ipfs/QmNtfjBAPYEFxXiHmY5kcPh9huzkwquHBcn9ZJHGe7hfaW
which is not working because "Account has been disabled."

![Screenshot from 2024-05-23 18-15-38](https://github.com/rairprotocol/rair-dapp/assets/26207079/e69fd8bb-d961-4b98-a371-880b77497731)

**Comment by sarora180673** [comment]
Please use this default 
https://rair.myfilebase.com/ipfs/QmcV94NurwfWVGpXTST1we8uDbYiVQamKe87WEHK6DRzqa

**Comment by sarora180673** [comment]
On, Batch metadata page same image url is also shown

![Uploading Screenshot from 2024-05-27 12-39-09.png…]()

**Comment by rairprotocol** [comment]
Remove all references to pinata and replaces with filebase. 

Does not cause issues just annoying in console log.

**Comment by rairprotocol** [comment]
suresh to double check if still happening

**Comment by sarora180673** [comment]
Not observed on latest dev branch
