### ISSUE TITLE
Check gasless resale - cannot estimate gas 

### ISSUE THREAD

**Issue by rairprotocol** [rairprotocol/rair-dapp#43]
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: Resale: Invalid withdraw request", method="estimateGas", transaction={"from":"0x3fD4268B03cce553f180E77dfC14fde00271F9B7","to":"0x58795f50b50d492C4252B9BBF78485EF4043FF3E","value":{"type":"BigNumber","hex":"0x5af3107a4000"},"data":"0x46b51ea50000000000000000000000008a3b517e536dc5eb5036de472d2c100a77551a4a0000000000000000000000003fd4268b03cce553f180e77dfc14fde00271f9b7000000000000000000000000f3fc93b77a1a39610aa800734dfd017ca293e53d000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000005af3107a40000000000000000000000000003fd4268b03cce553f180e77dfc14fde00271f9b700000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000041cd5bcd33eee80a6d81dcbe6a4e8a02d7dc5f3b8aabfc3e83e950c847e82b2ba618dc809251dbb63abf33f3363dccb1fb185fa0a963c4bf494b9223be204ce9be1c00000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted: Resale: Invalid withdraw request","data":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000020526573616c653a20496e76616c69642077697468647261772072657175657374","cause":null}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at rc.makeError (index-vu9U__Kc.js:109:73630)
    at rc.throwError (index-vu9U__Kc.js:109:73748)
    at pDe (index-vu9U__Kc.js:112:128401)
    at qC.<anonymous> (index-vu9U__Kc.js:112:137871)
    at Generator.throw (<anonymous>)
    at c (index-vu9U__Kc.js:112:127572)

**Comment by sarora180673** [comment]
gasless resale is working on QA server. It seems some issue with variables is causing this issue on rair.market

**Comment by rairprotocol** [comment]
works on localhost. more of a devops issue in the k8 setup.

**Comment by rairprotocol** [comment]
Keep open. Will investigate Kubernetes setup with AA and how that is different than single VM. If K8s cause issues with any of the AA gas functions (mint, resale, etc)

**Comment by rairprotocol** [comment]
Only kubernetes issue for gas estimation.

**Comment by RAIReth** [comment]
Will re open if re appears on kube setup

**Comment by RAIReth** [comment]
Gasless currently deprecated. If pay gas via AA flow it works
