### ISSUE TITLE
Release deliverables and pushing to main from dev

### ISSUE THREAD

**Issue by rairprotocol** [rairprotocol/rair-dapp#48]
Config issues around pushing stable version to main

**Comment by rairprotocol** [comment]
partially solved! Suresh figured out how to merge dev to main via intermediate branch :)

**Comment by rairprotocol** [comment]
Best practices on naming releases

**Comment by RAIReth** [comment]
lets make another release before next hackathon (end of current sprint 8/30)

**Comment by RAIReth** [comment]
Will reopen RE the SDK
