### ISSUE TITLE
Investigate frontend performance for image loading (Figure out issue referencing to master issue)

### ISSUE THREAD

**Issue by SeanM322** [rairprotocol/rair-dapp#50]
Investigate frontend performance for image loading to see if there are improvements to speed / reliability. (will get default image switched out)

**Comment by rairprotocol** [comment]
three places load from. alchemy cdn, gcp bucket, filebase - check if 1 is faster??

what determines the priority in which assets load. What is this 14 second rair.market/api/0xcontract0-60 taking all the time. 

how does the 

doesn't matter (5kb-30kb so small)


alchemy-cdn. small . webp (thumbnail)

alchemy-cdn. small . webp (full size)

**Comment by rairprotocol** [comment]
performance is more than just images. Arsenii found alchemy is best for fastest loading over bucket and filebase.

Javascripts are too big (8mb) - need to figure out how to reduce their size.

**Comment by rairprotocol** [comment]
@ #58

**Comment by rairprotocol** [comment]
Should put everything in branch 58
