### ISSUE TITLE
"cannot get total supply" while importing Base Blockchain external contracts

### ISSUE THREAD

**Issue by sarora180673** [rairprotocol/rair-dapp#53]
Scenario :  Try to import external contract  on Base Blockchain  
e.g., 0x4beeb0d76f06eab4cef96f1272625dfe15e85a61
0x67689883c97f65a6c95f5a2fd61b0ec9a71f3cbc

Observation:     "cannot get total supply"  error displayed on UI

rairnode logs:
6:46:44 AM web.1 |  POST /api/contracts/import/ 200 5.155 ms - 16
6:46:44 AM web.1 |  2024-06-05T06:46:44.534Z [error] : [ethers/importContractData.js] [object Object] 

![Screenshot from 2024-06-05 11-52-15](https://github.com/rairprotocol/rair-dapp/assets/26207079/5c846cb4-595d-4f05-be7e-e6847cee5839)

**Comment by jmsm412** [comment]
0x4beeb0d76f06eab4cef96f1272625dfe15e85a61 is an 1155 contract, which is not supported.
<img width="421" alt="image" src="https://github.com/rairprotocol/rair-dapp/assets/41866416/e51387a4-fe21-4d81-aca6-235d8b23e3cd">

**Comment by sarora180673** [comment]
![Screenshot from 2024-06-10 21-48-29](https://github.com/rairprotocol/rair-dapp/assets/26207079/b71ffdef-22ea-49eb-9099-972418ab6e7b)
