### ISSUE TITLE
Adapt Selenium Automation scripts with latest UI

### ISSUE THREAD

**Issue by sarora180673** [rairprotocol/rair-dapp#54]

**Comment by rairprotocol** [comment]
Ongoing issue that needs to stay open. So that scripts match evolving UI.

**Comment by rairprotocol** [comment]
TBD figure out github actions yaml to keep moving this issue over from sprint to sprint

**Comment by rairprotocol** [comment]
notifications make it so script cannot activate and find the elements to click on.

**Comment by rairprotocol** [comment]
2FA disabled still giving errors. try to make script to auto buy 1 free base 1 free polygon nft on rairprotocol.xyz twice per week.

**Comment by RAIReth** [comment]
Selenium script works for core workflow. Whenever modification is required will reopen
