### ISSUE TITLE
Default color scheme of video upload section on Demo upload page

### ISSUE THREAD

**Issue by sarora180673** [rairprotocol/rair-dapp#68]
After we select video for upload on Demo upload page, some text is not visible on the video section and also default color iis not matching with the Dark/light theme of the page

![Screenshot from 2024-06-18 12-00-43](https://github.com/rairprotocol/rair-dapp/assets/26207079/907bfc4b-2627-4950-883d-2c4761f87693)
![Screenshot from 2024-06-18 12-01-13](https://github.com/rairprotocol/rair-dapp/assets/26207079/51ff9462-6b16-4a1a-8119-32c7bbb2902a)

**Comment by rairprotocol** [comment]
solved!
