### ISSUE TITLE
Transition ticketing system from Jira to Github Issues

### ISSUE THREAD

**Issue by rairprotocol** [rairprotocol/rair-dapp#7]
Figure out how Github Issues works

**Comment by rkotchamp** [comment]
Pls can you be more specific on the kind of help you would need on this issue?

**Comment by rairprotocol** [comment]
reopening!

**Comment by rairprotocol** [comment]
> Pls can you be more specific on the kind of help you would need on this issue?

No help in particular - need to migrate tickets on our end - would love any feedback you have if you're able to run docker okay

**Comment by rairprotocol** [comment]
we did it!
