### ISSUE TITLE
Error message on navigating to  Profile Page from Home page

### ISSUE THREAD

**Issue by sarora180673** [rairprotocol/rair-dapp#79]
Sometimes, error message is observed on navigating to Profile

![Screenshot from 2024-06-26 20-01-25](https://github.com/rairprotocol/rair-dapp/assets/26207079/a2cda391-d290-436c-8dc6-9d09261182ba)

**Comment by rairprotocol** [comment]
Timeout related issue? If you stay on profile page for too long it will error.

**Comment by rairprotocol** [comment]
Happens on desktop and mobile

**Comment by RAIReth** [comment]
still happening on mobile view and rair.market
