### ISSUE TITLE
Update theming elements (header, text color to primary button color for icons)

### ISSUE THREAD

**Issue by rairprotocol** [rairprotocol/rair-dapp#94]
Investigate header to match "secondary color" - currently doesn't change

Update theming for all icons (hamburger menu, search magnifying glass, filters, etc) to "primary button color" instead of "text color"

![Screenshot 2024-07-08 090507](https://github.com/rairprotocol/rair-dapp/assets/73792201/6f70d2b2-b57b-41d9-8419-778fce0f156c)

**Comment by sarora180673** [comment]
Please also check on Mobile. In few cases e.g., Connect Button is shown correctly on Desktop but not on mobile

![Screenshot_2024-07-08-21-35-19-393_com android chrome](https://github.com/rairprotocol/rair-dapp/assets/26207079/09c1c565-2b4a-4d56-8bf4-5f87a8b9e9cb)

**Comment by rairprotocol** [comment]
Ready for merge!!
