### ISSUE TITLE
Page title - Hotdrops

### ISSUE THREAD

**Issue by sarora180673** [rairprotocol/rair-dapp#96]
VITE_HTML_META_TITLE=Hot Drops

Above variable defined in rair-front/.env

On loading page, Page title is shown as "Hot Drops" but then changes back to "RAIR Technologies"

[Screencast from 08-07-24 09:20:54 PM IST.webm](https://github.com/rairprotocol/rair-dapp/assets/26207079/1576edfc-a7fe-43a6-8ddf-cde9391a8c8f)

**Comment by sarora180673** [comment]
same issue was observed on https://opencarbon.market/ 

We need generic solution and not just Hotdrops specific

**Comment by rairprotocol** [comment]
Sean to investigate this sprint

**Comment by sarora180673** [comment]
@SeanM322 On latest dev branch, page title changes from Rair Technologies to Hotdrops Technologies after page is loaded/

env variables defined are:

VITE_TESTNET=false

**Comment by RAIReth** [comment]
comment out Testnet variable = false. Something is wrong with testnet variable  

Always show meta title and not switch back to default title
